### PR TITLE
fix: cowork existsSync crash on 1.3109+ and unblock node-pty terminal

### PR DESCRIPTION
**Pull request by Joost-Maker**
Two independent Linux bugs surfaced while debugging Cowork on Claude Desktop 1.3109.0 (Pop!_OS 24.04, amd64). Both fixed and verified end-to-end on my machine.

## Bug 1: `TypeError: e.existsSync is not a function` on Cowork VM boot

**Issue:** #418

`patch_cowork_linux()` Patch 9 extracts six minified variable names from the win32 block and uses them to template a Linux smol-bin copy block. The extraction regexes used `(\w+)`, which doesn't match `$` — but JS identifiers can start with `$`, `_`, or a letter.

In Claude 1.3109.0, upstream renamed the local fs reference inside `startVM`'s win32 block from `e` to `$e`, presumably to avoid shadowing the function parameter `e` (which is the options object):

```js
// Win32 block in 1.3109.0 (excerpt)
if (process.platform === "win32") {
    const x = Bre(), U = ae.join(process.resourcesPath, `smol-bin.${x}.vhdx`), J = ae.join(r, "smol-bin.vhdx");
    if ($e.existsSync(U)) {                       // <-- fs is $e, not e
        await SL.pipeline($e.createReadStream(U), SX(J))
        ...
    }
}
```

The existing `(\w+)\.existsSync\(` regex scans `$e.existsSync(U)`, skips the `$`, captures just `e`, and Patch 9 then injects:

```js
if (process.platform === "linux") {
    ...
    e.existsSync(_ls) ? ... : ...   // e is the options object → TypeError
}
```

The "patch's injection works in 1.2773 but breaks in 1.3109" pattern is exactly this. There's no upstream Linux block to strip — the buggy block we've all been hitting **is the patcher's own injection**, made buggy by the regex missing `$`.

**Fix:** widen all six extraction patterns from `(\w+)` to `([$\w]+)`. Also widened the adjacent unanchored matchers in `archMatch` for consistency.

**Defensive bonus:** added a brace-counting strip step before injection, so if a future upstream version emits its own `if(process.platform==="linux"){...}` block right after the win32 close brace, we remove it before injecting our correctly-wired version. No-op on current upstream; future-proofing.

**Verified:** clean rebuild now logs `vars: path=ae fs=$e log=qe stream=SL arch=Bre bundle=r` and the asar's injected block contains `$e.existsSync(_ls)`. Cowork starts cleanly: `[VM:start] Startup complete, total time: 1242ms`, the VM agent spawns, and prompts get responses end-to-end.

## Bug 2: `Failed to load node-pty` (terminal in Claude Code mode)

Surfaced after fixing Bug 1, when the app reached Claude Code mode with a working shell session attempt. Error:

```
Failed to load node-pty {
  error: Error: Failed to load native module: pty.node, checked: build/Release, build/Debug, prebuilds/linux-x64:
    Error: Cannot find module './prebuilds/linux-x64//pty.node'
  - /usr/lib/claude-desktop/.../app.asar/node_modules/node-pty/lib/utils.js
}
```

**Root cause:** `install_node_pty()` copied only `lib/` and `package.json` into `app.asar.contents/.../node-pty/`, and `finalize_app_asar()` packed app.asar without `--unpack`. The `.node` binaries were then separately dropped into `app.asar.unpacked/.../node-pty/build/Release/`.

The asar manifest therefore had no entry for `node-pty/build/` at all. When node-pty's loader (inside the asar) does `require('../build/Release/pty.node')`, Electron's asar→.unpacked redirect never fires because the redirect requires a manifest entry annotated as unpacked. Result: MODULE_NOT_FOUND despite the binary existing on disk.

**Fix:**
1. `install_node_pty()`: also stage `$pty_src_dir/build/` into `app.asar.contents/node_modules/node-pty/`.
2. `finalize_app_asar()`: pass `--unpack '**/*.node'` to `asar pack` so the binaries get moved into `app.asar.unpacked/` AND recorded in the manifest as unpacked.

**Verified:** new asar manifest now reports
```
UNPACKED: /node_modules/node-pty/build/Release/pty.node
UNPACKED: /node_modules/node-pty/build/Release/conpty.node
UNPACKED: /node_modules/node-pty/build/Release/conpty_console_list.node
```
and Claude Code's terminal loads successfully. Tested by running interactive shell sessions in Claude Code mode of the rebuilt .deb.

The pre-existing copy-to-.unpacked step at the bottom of `finalize_app_asar()` is now redundant but harmless (writes the same bytes). Left in place for now to minimize diff and preserve the `--node-pty-dir` (Nix) flow, where the explicit copy may still be load-bearing.

## Test plan

- [x] `./build.sh --build deb --clean no` against upstream 1.3109.0 produces a working .deb
- [x] Installed .deb on Pop!_OS 24.04 (amd64)
- [x] Cowork mode: VM boots, agent spawns, prompts answered (verified `[VM:start] Startup complete` in `cowork_vm_node.log` + actual chat in the UI)
- [x] Claude Code mode: terminal sessions start without the node-pty error
- [ ] Smoke test on an arm64 machine (don't have one handy; the fix is arch-agnostic)
- [ ] Smoke test against an older Claude Desktop version where fs is just `e` not `$e` — `[$\w]+` is a strict superset of `\w`, so existing extraction still works

## Notes

- Both fixes are minimal and surgical; they don't change any control flow that was working.
- The two commits are atomic — each can be reverted independently if needed.

---
Generated with [Claude Code](https://claude.ai/code)
Co-Authored-By: Claude Sonnet 4.6 <noreply@anthropic.com>
85% AI / 15% Human
Claude: bug analysis (asar/JS spelunking, regex root cause, node-pty manifest investigation), patch authoring, build/test loop, commit + PR drafting
Human: ran the rebuilds, ran sudo installs, smoke-tested Cowork & terminal in the UI, decided strategy

### CODE REVIEW

**Comment by shawnvanderveer** [comment]
Thanks, worked like a charm Ubuntu 25.10

**Review by aaddrick — APPROVED** [review]
Hey Joost-Maker, this is solid work. Both fixes are clean, the root cause analysis in the PR description is thorough, and the commit messages are some of the best I've seen on this repo. Approving and merging.

The `$e` capture issue was the #1 reported problem this week across six separate issues (#413, #415, #417, #418, #423, #409). Widening to `[$\w]+` is the right call and it's a strict superset, so older versions where the var is just `e` still work fine.

The node-pty asar manifest fix is the kind of thing that's easy to miss. The binaries were on disk but the manifest didn't know about them, so Electron's redirect never fired. Staging `build/` and adding `--unpack '**/*.node'` is the correct approach. 

A couple minor things I'll track as follow-ups (not blocking this merge):

1. The brace-counting strip for future upstream Linux blocks is a nice defensive addition. One edge case: it doesn't track whether braces appear inside string literals or template strings. Probably fine for minified output where that's rare, but worth a comment in the code so future readers know the limitation.

2. The old manual copy-to-unpacked step in `finalize_app_asar()` is now redundant since `--unpack` handles it. Harmless for now as you noted, but we can clean it up in a follow-up once we verify the Nix flow doesn't depend on it.

I also want to give a shout-out to @RayCharlizard (#414) and @Smilez1985 (#419) who both jumped on the regex fix quickly. Having three independent contributors identify and fix the same root cause within hours of each other is great to see. I'll close #414 and #419 referencing this PR since it bundles the additional node-pty fix and has end-to-end user confirmation.

Thanks for the quick turnaround on this. Merging now.

---
Written by Claude Opus 4.6 via [Claude Code](https://claude.ai/code)
